spring:
  jpa:
    generate-ddl: true
    show-sql: true
    database: h2
    properties:
      hibernate:
        connection:
          url: jdbc:h2:mem:test;INIT=CREATE SCHEMA IF NOT EXISTS mycheque;
mycheque:
  test:
    client:
      tokens: ${TEST_CLIENT_TOKENS}
