spring:
  application:
    name: mycheque
  data:
    mongodb:
      uri: ${MONGO_URI}
  datasource:
    url: ${JDBC_URL}
    username: ${PG_USERNAME}
    password: ${PG_PASSWORD}
  jpa:
    show-sql: true
    open-in-view: false

springdoc:
  swagger-ui:
    url: open-api.yml
