package com.mycheque.service.configure;

import java.util.Map;
import java.util.List;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

import com.mycheque.util.Maps;
import com.mycheque.util.Assert;

import com.mycheque.client.ClientTemplate;
import com.mycheque.client.RequestBodyAttributes;

import com.mycheque.datatransfer.accept.ReceiptDefinition;

import com.mycheque.mapping.ClientEntityExtractor;
import com.mycheque.mapping.RequestBodyAttributesMappingStrategy;

import com.mycheque.service.integrate.OncePerRequestIntegration;
import com.mycheque.service.integrate.OncePerHttpRequestIntegration;
import com.mycheque.service.integrate.OncePerRequestIntegrationProvider;

/**
 * The service infrastructure configuration class.
 *
 * @author resxnvnce
 */
@Configuration
public class ServiceConfiguration {

    /**
     * The client template, defined at its configuration class.
     */
    private final ClientTemplate template;

    /**
     * The <b>JSON</b> entities extractor, generated by MapStruct.
     */
    private final ClientEntityExtractor extractor;

    /**
     * All the implementations of {@link RequestBodyAttributesMappingStrategy},
     * mapped. Each of them should be annotated with stereotype annotation.
     */
    private final Map<ReceiptDefinition.By, RequestBodyAttributesMappingStrategy> strategiesMap;

    /**
     * Constucts a {@code ServiceConfiguration} bean.
     *
     * @param template     the client template to execute <b>HTTP POST</b> requests.
     * @param extractor  the <b>JSON</b> entities extractor.
     * @param strategies the {@code RequestBodyAttributes} mapping strategies, unmapped.
     */
    public ServiceConfiguration(ClientTemplate template,
                                ClientEntityExtractor extractor,
                                List<RequestBodyAttributesMappingStrategy> strategies) {
        this.template = template;
        this.extractor = extractor;
        this.strategiesMap = Maps.mapToIdentity(strategies.stream(), RequestBodyAttributesMappingStrategy::basedOn);
    }

    /**
     * Constructs a {@link OncePerRequestIntegration} prototype bean by using the supplied factory.
     *
     * @param factory a {@code RequestBodyAttributes.Factory} to instantiate a prototype integration.
     * @return a {@code OncePerRequestIntegration} prototype bean.
     */
    OncePerRequestIntegration getIntegration(RequestBodyAttributes.Factory factory) {
        Assert.args(factory != null, () -> "factory must not be null");
        return new OncePerHttpRequestIntegration(this.getStrategiesMap(), factory, this.template, this.extractor);
    }

    /**
     * The {@link OncePerRequestIntegration} prototype bean factory.
     *
     * @return the function producing the {@code OncePerRequestIntegration} prototype beans.
     */
    @Bean
    OncePerRequestIntegrationProvider getIntegrationProvider() {
        return this::getIntegration;
    }

    /**
     * Returns the {@link RequestBodyAttributesMappingStrategy} beans, accumulated into a {@link Map}.
     *
     * @return the {@code RequestBodyAttributes} mapping strategies, mapped by their
     *         {@linkplain RequestBodyAttributesMappingStrategy#basedOn() definition method}.
     */
    @Bean
    Map<ReceiptDefinition.By, RequestBodyAttributesMappingStrategy> getStrategiesMap() {
        return this.strategiesMap;
    }
}
