package com.mycheque.domain;

import java.util.Set;
import java.util.StringJoiner;

import com.mycheque.lang.Nullable;

import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.persistence.Entity;
import jakarta.persistence.Column;
import jakarta.persistence.EnumType;
import jakarta.persistence.OneToMany;
import jakarta.persistence.FetchType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;

import com.mycheque.mapping.support.Default;

import com.mycheque.datatransfer.result.MutationDescription;

import com.mycheque.util.hibernate6.NamedEnum;
import com.mycheque.util.hibernate6.HibernateProxiesAware;

import org.springframework.data.jpa.domain.Specification;

import org.springframework.security.core.GrantedAuthority;

/**
 * An entity representing the project user.
 * <p>
 * Has multiple {@linkplain #getReceipts() receipts} in their possession,
 * a unique {@linkplain #getUsername() username}, which is modifiable,
 * and an updatable {@linkplain #getThirdpartyToken() token}
 * to be able to send requests via the client module.
 *
 * @author resxnvnce
 */
@Table(name = "customer", schema = "public")
public @Entity class Customer implements HibernateProxiesAware {

    /**
     * The user identifier, autogenerated by the persistence provider.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "id", unique = true, nullable = false, updatable = false)
    private @Nullable Long id;

    /**
     * The username, which is unique among all the {@code Customers}
     * and may be changed over time.
     */
    @Column(name = "username", unique = true, nullable = false, length = 30)
    private String username;

    /**
     * The user password, which is always stored in an encrypted form.
     */
    @Column(name = "password", nullable = false, length = 61)
    private String password;

    /**
     * The user third-party token, which is required to perform a request
     * via the client module and also is unique among all the users.
     */
    @Column(name = "thirdparty_token", unique = true, nullable = false, length = 63)
    private String thirdpartyToken;

    /**
     * The user role, which defines the <i>MyCheque API</i> endpoints they have access to.
     * <p>
     * Defaults to {@link Role#USER}.
     */
    @Column(name = "role", nullable = false, length = 31, columnDefinition = "customer_role")
    @NamedEnum // resolves the SQLGrammarException issue
    @Enumerated(EnumType.STRING)
    private Role role = Role.USER;

    /**
     * The user {@linkplain Receipt receipts}. Fetched lazily by default.
     */
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "customer", orphanRemoval = true)
    private @Nullable Set<Receipt> receipts;

    /**
     * Returns a description of this {@code Customer} mutation.
     *
     * @return a {@link MutationDescription} exposing the public properties that have been changed.
     */
    public MutationDescription toMutationDescription() {
        return new MutationDescription(this.username, this.thirdpartyToken);
    }

    /**
     * Returns a matching {@link Specification} for the
     * partial search queries, using this {@code Customer}'s id.
     *
     * @return a {@code Specification} that matches this customer, never {@code null}.
     */
    public Specification<Receipt> toReceiptSpecification() {
        if (this.id == null) {
            return Specification.where(null);
        }

        return (root, query, cb) -> cb.equal(root.join("customer").get("id"), this.id);
    }

    /* Constructors */

    /**
     * The protected constructor only to be invoked by
     * the persistence provider or by Spring framework.
     */
    protected Customer() {
    }

    /**
     * Constructs a new {@code Customer} with the given username and password.
     *
     * @param username the username to authorize the {@code Customer}.
     * @param password the password to authenticate the {@code Customer}.
     */
    @Default // the primary constructor for MapStruct to use
    public Customer(String username, String password) {
        setUsername(username);
        setPassword(password);
    }

    /**
     * Constructs a new {@code Customer} with the given username, password and
     * the third-party token.
     *
     * @param username        the username to authorize the {@code Customer}.
     * @param password        the password to authenticate the {@code Customer}.
     * @param thirdpartyToken the token required for the client module usage.
     */
    public Customer(String username, String password, String thirdpartyToken) {
        setUsername(username);
        setPassword(password);
        setThirdpartyToken(thirdpartyToken);
    }

    /* Roles */

    /**
     * Enum describing the {@code Customer} roles hierarchy.
     */
    public enum Role implements GrantedAuthority {

        /**
         * The default role, given to each new {@code Customer}.
         */
        USER,

        /**
         * The role of a staff member.
         * <p>
         * <i>Grants the access to the several secured endpoints.</i>
         */
        STAFF,

        /**
         * The role of a limited number of staff members.
         * <p>
         * <i>Grants the access to the several private endpoints,
         * as well as the endpoints a staff member has access to.</i>
         */
        ADMIN;

        @Override
        public String getAuthority() {
            return this.name();
        }
    }

    /* Getters & Setters */

    /**
     * Returns the {@code Customer} identifier, assigned by the persistence provider.
     *
     * @return the entity identifier.
     */
    @Nullable
    @Override
    public Long getId() {
        return this.id;
    }

    /**
     * Not intended to use explicitly.
     *
     * @deprecated Identifier is only assigned by the persistence provider.
     */
    @Deprecated
    protected void setId(@Nullable Long id) {
        this.id = id;
    }

    /**
     * Returns the username.
     * Note that {@code Customers} may change it over time.
     *
     * @return this {@code Customer}'s username.
     */
    public String getUsername() {
        return this.username;
    }

    /**
     * Set this {@code Customer}'s username.
     *
     * @param username the username to be used by this
     *                 {@code Customer} to authorize.
     */
    public void setUsername(String username) {
        this.username = username;
    }

    /**
     * Returns the password.
     * Note that {@code Customers} may change it over time.
     *
     * @return this {@code Customer}'s password.
     */
    public String getPassword() {
        return this.password;
    }

    /**
     * Set this {@code Customer}'s password.
     *
     * @param password the password to be used by this
     *                 {@code Customer} to authenticate.
     */
    public void setPassword(String password) {
        this.password = password;
    }

    /**
     * Returns the third-party token.
     * Note that {@code Customers} may change it over time.
     *
     * @return the token to be used by the client module.
     */
    public String getThirdpartyToken() {
        return this.thirdpartyToken;
    }

    /**
     * Set this {@code Customer}'s third-party token.
     *
     * @param thirdpartyToken the token to be used by this {@code Customer}.
     */
    public void setThirdpartyToken(String thirdpartyToken) {
        this.thirdpartyToken = thirdpartyToken;
    }

    /**
     * Returns the role of this {@code Customer}.
     *
     * @return the {@link Role}, defining their authorities.
     */
    public Role getRole() {
        return this.role;
    }

    /**
     * Set the role of this {@code Customer}.
     *
     * @param role the {@link Role}, defining their authorities.
     */
    public void setRole(Role role) {
        this.role = role;
    }

    /**
     * Returns a modifiable {@code Set} of the {@link Receipt}s
     * this customer has in their possession.
     *
     * @return the receipts of this {@code Customer}.
     */
    @Nullable
    public Set<Receipt> getReceipts() {
        return this.receipts;
    }

    /**
     * Not intended to use explicitly.
     *
     * @deprecated Explicit usage of this method may lead to an unexpected error.
     */
    @Deprecated
    protected void setReceipts(@Nullable Set<Receipt> receipts) {
        this.receipts = receipts;
    }

    /* java.lang.Object */

    /**
     * Proxy-aware {@code #hashCode()} method.
     *
     * @see HibernateProxiesAware#proxySafeHashCode()
     */
    @Override
    public final int hashCode() {
        return this.proxySafeHashCode();
    }

    /**
     * Proxy-aware {@code #equals(Object)} method.
     *
     * @see HibernateProxiesAware#proxySafeEquals(Object)
     */
    @Override
    public final boolean equals(Object o) {
        return this.proxySafeEquals(o);
    }

    /**
     * <b>This method is NOT proxy-aware</b>.
     */
    @Override
    public String toString() {
        return new StringJoiner(", ", Customer.class.getSimpleName() + "[", "]")
                .add("id=" + id)
                .add("role=" + role)
                .add("username='" + username + "'")
                .add("password='" + password + "'")
                .add("thirdpartyToken='" + thirdpartyToken + "'")
                .toString();
    }
}
