package com.mycheque.util.hibernate6;

import org.springframework.lang.Nullable;

import org.hibernate.proxy.HibernateProxy;

/**
 * Convenient utility interface JPA entities may extend in order to
 * get proxy-safe, {@linkplain #getId() id} based implementations of
 * {@link Object#equals(Object)} and {@link Object#hashCode()} methods.
 *
 * @author resxnvnce
 */
public interface HibernateProxiesAware {

    /**
     * The entity identifier to be used in equality checks
     * and the hash code evaluation.
     *
     * @return the entity unique identifier.
     *         May be {@code null} if it's autogenerated.
     */
    @Nullable
    Object getId();

    /**
     * Returns the {@linkplain #getId() id} based hash code of this entity.
     *
     * @return the id based hash code.
     */
    default int proxySafeHashCode() {
        return getId() != null ? getId().hashCode() : 0;
    }

    /**
     * Returns the runtime entity class, whether it is a proxy or not.
     *
     * @return the actual class of the entity.
     */
    default Class<?> getEntityClass() {
        return this instanceof HibernateProxy proxy ?
                proxy.getHibernateLazyInitializer().getPersistentClass() : getClass();
    }

    /**
     * Returns {@code true} if and only if {@code this} and {@code o} are the same
     * {@link Object}, or both have the same {@linkplain #getEntityClass()
     * entity class} and {@linkplain #getId() identifier}.
     *
     * @param o an object to be compared with {@code this} for equality.
     * @return {@code true} if the arguments are equal to each other
     *         and {@code false} otherwise.
     */
    default boolean proxySafeEquals(@Nullable Object o) {
        if (this == o) return true;
        return o instanceof HibernateProxiesAware hpa
                && getEntityClass() == hpa.getEntityClass()
                && getId() != null && getId().equals(hpa.getId());
    }
}
